# System HASS Module
#
# Provides local system monitoring and info.

media_player:

  - platform: kodi
    #name: laptop
    host: !secret laptop_ip

  - platform: clementine
    #name: clementine
    host: !secret laptop_ip

  # Used only for TTS, data not recorded
  - platform: mpd
    name: mpdlaptop
    host: !secret laptop_ip
    port: 6600
    password: !secret mediaplayer_mpdlaptop


sensor:
  - platform: glances
    name: Laptop Monitoring
    host: !secret laptop_ip
    resources:
      - 'disk_use_percent'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_free'
      - 'processor_load'
      #- 'temperature_core'
      #- 'process_running'
      #- 'process_total'
      #- 'process_thread'
      #- 'process_sleeping'

switch:

  - platform: command_line
    switches:
      laptop_display:
        friendly_name: Laptop Display
        command_on: ssh jlaptop "export DISPLAY=:0 && xset dpms force on"
        command_off: ssh jlaptop "export DISPLAY=:0 && xset dpms force off"
        command_state: ssh jlaptop "export DISPLAY=:0 && xset -q | grep 'Monitor is' | grep 'On' | echo $?"
        value_template: '{{ value == "0" }}'


